// Question and word banks for the Games Court.

/** [question, four choices, index of the right answer]. Well-established facts only, plus a few about the city. */
export const TRIVIA: [string, [string, string, string, string], number][] = [
  ['Who is the mayor of HermesCity?', ['Cass', 'Maia', 'Atlas', 'Tally'], 1],
  ['What is the currency of HermesCity called?', ['Obols', 'Coins', 'Beans', 'Shells'], 0],
  ['Where does every agent without a house have a room?', ['The Bank', 'The Workshop', 'The Lodging House', 'The Merchants\' Guild'], 2],
  ['Which station in HermesCity hands out routing tasks?', ['The Route Office', 'The Logic Spire', 'The Cipher Room', 'The Exchange'], 0],
  ['In knights and knaves puzzles, knaves always...', ['tell the truth', 'lie', 'stay silent', 'ask questions'], 1],
  ['What is the chemical symbol for gold?', ['Go', 'Gd', 'Au', 'Ag'], 2],
  ['How many continents are there on Earth, by the most common count?', ['5', '6', '7', '8'], 2],
  ['What is the largest planet in our solar system?', ['Saturn', 'Jupiter', 'Neptune', 'Earth'], 1],
  ['Which planet is known as the Red Planet?', ['Venus', 'Mars', 'Mercury', 'Jupiter'], 1],
  ['What is the boiling point of water at sea level in Celsius?', ['90', '100', '110', '120'], 1],
  ['How many sides does a hexagon have?', ['5', '6', '7', '8'], 1],
  ['What is the square root of 144?', ['10', '11', '12', '14'], 2],
  ['Which ocean is the largest?', ['Atlantic', 'Indian', 'Arctic', 'Pacific'], 3],
  ['What is the capital of Japan?', ['Osaka', 'Kyoto', 'Tokyo', 'Sapporo'], 2],
  ['What is the capital of Australia?', ['Sydney', 'Melbourne', 'Canberra', 'Perth'], 2],
  ['What is the capital of Canada?', ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'], 1],
  ['Which is the longest river in South America?', ['Amazon', 'Paraná', 'Orinoco', 'Magdalena'], 0],
  ['Who wrote "Romeo and Juliet"?', ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'], 1],
  ['Who painted the Mona Lisa?', ['Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Donatello'], 2],
  ['What gas do plants take in for photosynthesis?', ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Helium'], 2],
  ['How many bones are in the adult human body?', ['186', '206', '226', '246'], 1],
  ['What is the hardest natural substance?', ['Quartz', 'Diamond', 'Granite', 'Iron'], 1],
  ['What is the freezing point of water in Fahrenheit?', ['0', '16', '32', '40'], 2],
  ['How many minutes are in a day?', ['1,240', '1,440', '1,640', '1,840'], 1],
  ['Which animal is the largest mammal?', ['African elephant', 'Blue whale', 'Giraffe', 'Hippopotamus'], 1],
  ['How many legs does a spider have?', ['6', '8', '10', '12'], 1],
  ['What is 7 times 8?', ['54', '56', '58', '64'], 1],
  ['What is the smallest prime number?', ['0', '1', '2', '3'], 2],
  ['Which language has the most native speakers?', ['English', 'Spanish', 'Mandarin Chinese', 'Hindi'], 2],
  ['In computing, what does CPU stand for?', ['Central Processing Unit', 'Computer Power Unit', 'Core Program Utility', 'Central Program Unit'], 0],
  ['What does HTML stand for?', ['HyperText Markup Language', 'High Transfer Machine Language', 'Hyperlink Text Mode Language', 'Home Tool Markup Language'], 0],
  ['How many bits are in a byte?', ['4', '8', '16', '32'], 1],
  ['What is 2 to the power of 10?', ['512', '1,000', '1,024', '2,048'], 2],
  ['In which year did humans first land on the Moon?', ['1965', '1969', '1972', '1975'], 1],
  ['Which country gifted the Statue of Liberty to the United States?', ['England', 'France', 'Spain', 'Italy'], 1],
  ['Which is the tallest mountain above sea level?', ['K2', 'Kangchenjunga', 'Mount Everest', 'Denali'], 2],
  ['What is the largest desert in the world, including polar deserts?', ['Sahara', 'Gobi', 'Antarctica', 'Arabian'], 2],
  ['What colour do you get by mixing blue and yellow?', ['Purple', 'Green', 'Orange', 'Brown'], 1],
  ['How many strings does a standard violin have?', ['4', '5', '6', '7'], 0],
  ['Which instrument has 88 keys in its standard modern form?', ['Organ', 'Harpsichord', 'Piano', 'Accordion'], 2],
  ['What is the main ingredient of guacamole?', ['Tomato', 'Avocado', 'Pea', 'Lime'], 1],
  ['Which vitamin does sunlight help the body make?', ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'], 3],
  ['What is the largest organ of the human body?', ['Liver', 'Brain', 'Skin', 'Lungs'], 2],
  ['How many hearts does an octopus have?', ['1', '2', '3', '4'], 2],
  ['Which bird is known for mimicking human speech?', ['Parrot', 'Owl', 'Sparrow', 'Pelican'], 0],
  ['What is the fastest land animal?', ['Lion', 'Cheetah', 'Pronghorn', 'Horse'], 1],
  ['In chess, which piece can only move diagonally?', ['Rook', 'Knight', 'Bishop', 'King'], 2],
  ['How many squares are on a chessboard?', ['36', '49', '64', '81'], 2],
  ['What shape has three sides?', ['Square', 'Triangle', 'Pentagon', 'Circle'], 1],
  ['What is the sum of the angles in a triangle?', ['90 degrees', '180 degrees', '270 degrees', '360 degrees'], 1],
  ['What is pi rounded to two decimal places?', ['3.12', '3.14', '3.16', '3.41'], 1],
  ['Which planet has the most prominent rings?', ['Jupiter', 'Uranus', 'Saturn', 'Neptune'], 2],
  ['What is the closest star to Earth?', ['Proxima Centauri', 'Sirius', 'The Sun', 'Alpha Centauri A'], 2],
  ['How many planets are in our solar system?', ['7', '8', '9', '10'], 1],
  ['What is the capital of Italy?', ['Milan', 'Venice', 'Rome', 'Naples'], 2],
  ['What is the capital of Spain?', ['Barcelona', 'Madrid', 'Seville', 'Valencia'], 1],
  ['What is the capital of Egypt?', ['Alexandria', 'Cairo', 'Giza', 'Luxor'], 1],
  ['What is the capital of Kenya?', ['Mombasa', 'Nairobi', 'Kisumu', 'Nakuru'], 1],
  ['What is the capital of Brazil?', ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'], 2],
  ['What is the capital of Germany?', ['Munich', 'Hamburg', 'Berlin', 'Frankfurt'], 2],
  ['Which country has the largest land area?', ['Canada', 'China', 'United States', 'Russia'], 3],
  ['Which is the smallest country in the world by area?', ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'], 1],
  ['Which metal is liquid at room temperature?', ['Lead', 'Mercury', 'Tin', 'Zinc'], 1],
  ['What is the chemical formula for water?', ['H2O', 'CO2', 'O2', 'NaCl'], 0],
  ['What force keeps the planets in orbit around the Sun?', ['Magnetism', 'Friction', 'Gravity', 'Electricity'], 2],
  ['Who proposed the theory of general relativity?', ['Isaac Newton', 'Albert Einstein', 'Niels Bohr', 'Galileo Galilei'], 1],
  ['What is the most abundant gas in Earth\'s atmosphere?', ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon'], 2],
  ['How many days are in a leap year?', ['364', '365', '366', '367'], 2],
  ['Which month has 28 days in a common year?', ['January', 'February', 'April', 'November'], 1],
  ['How many weeks are in a year, rounded down?', ['50', '51', '52', '53'], 2],
  ['What do bees make?', ['Milk', 'Honey', 'Silk', 'Wax only'], 1],
  ['Which fruit has its seeds on the outside?', ['Blueberry', 'Strawberry', 'Grape', 'Cherry'], 1],
  ['What is a baby frog called?', ['Cub', 'Kit', 'Tadpole', 'Fry'], 2],
  ['How many players are on a soccer team on the field?', ['9', '10', '11', '12'], 2],
  ['In which sport would you perform a slam dunk?', ['Volleyball', 'Basketball', 'Tennis', 'Rugby'], 1],
  ['How many rings are on the Olympic flag?', ['4', '5', '6', '7'], 1],
  ['What is the opposite of "ancient"?', ['Old', 'Modern', 'Antique', 'Historic'], 1],
  ['Which word is a synonym of "rapid"?', ['Slow', 'Quick', 'Calm', 'Heavy'], 1],
  ['What is the plural of "mouse" (the animal)?', ['Mouses', 'Mice', 'Meese', 'Mousen'], 1],
  ['What is 15% of 200?', ['15', '20', '30', '45'], 2],
  ['What is 1,000 divided by 8?', ['120', '125', '130', '150'], 1],
  ['What is the next number: 2, 4, 8, 16, ...?', ['18', '24', '30', '32'], 3],
  ['Which number is divisible by 9?', ['243', '244', '245', '247'], 0],
  ['In binary, what is 1010 in decimal?', ['8', '10', '12', '20'], 1],
  ['What does the "www" in a web address stand for?', ['World Wide Web', 'Wide World Web', 'Web World Wide', 'World Web Wide'], 0],
  ['Which is not a programming language?', ['Python', 'Rust', 'Cobra Kai', 'Java'], 2],
  ['Which of these is a prime number?', ['21', '27', '29', '33'], 2],
  ['What is the Roman numeral for 50?', ['V', 'X', 'L', 'C'], 2],
  ['Which is the only even prime number?', ['0', '2', '4', '6'], 1],
  ['Which planet is closest to the Sun?', ['Venus', 'Mercury', 'Mars', 'Earth'], 1],
  ['What do caterpillars turn into?', ['Beetles', 'Butterflies or moths', 'Bees', 'Spiders'], 1],
  ['Which of these animals is a marsupial?', ['Koala', 'Panda', 'Otter', 'Badger'], 0],
  ['Which of these is a primary colour of light?', ['Yellow', 'Green', 'Purple', 'Orange'], 1],
  ['How many hours are in a week?', ['148', '158', '168', '178'], 2],
  ['Which direction does the Sun rise from?', ['North', 'South', 'East', 'West'], 2],
  ['What is frozen water called?', ['Steam', 'Ice', 'Dew', 'Mist'], 1],
  ['Which tool measures temperature?', ['Barometer', 'Thermometer', 'Odometer', 'Speedometer'], 1],
  ['What do you call a word that reads the same backwards, like "level"?', ['Anagram', 'Palindrome', 'Acronym', 'Homonym'], 1],
  ['How many letters are in the English alphabet?', ['24', '25', '26', '27'], 2],
  ['Which is the largest continent by area?', ['Africa', 'Asia', 'North America', 'Europe'], 1],
];

/** Themed words for Word Hunt. A theme's name makes a good one-word clue for its words (and is never on the board). */
export const WORD_THEMES: Record<string, string[]> = {
  fruit: ['apple', 'pear', 'plum', 'cherry', 'mango', 'lemon', 'grape', 'peach', 'melon', 'kiwi'],
  farm: ['cow', 'pig', 'sheep', 'goat', 'horse', 'duck', 'hen', 'donkey', 'barn', 'tractor'],
  ocean: ['whale', 'shark', 'crab', 'coral', 'wave', 'tide', 'reef', 'squid', 'octopus', 'shell'],
  weather: ['rain', 'snow', 'storm', 'cloud', 'thunder', 'fog', 'hail', 'breeze', 'frost', 'rainbow'],
  music: ['piano', 'drum', 'violin', 'guitar', 'flute', 'trumpet', 'harp', 'choir', 'song', 'melody'],
  kitchen: ['spoon', 'knife', 'fork', 'oven', 'kettle', 'pan', 'plate', 'bowl', 'whisk', 'cup'],
  space: ['star', 'planet', 'moon', 'comet', 'rocket', 'orbit', 'galaxy', 'meteor', 'astronaut', 'nebula'],
  tools: ['hammer', 'saw', 'drill', 'wrench', 'nail', 'screw', 'chisel', 'ladder', 'shovel', 'rake'],
  gems: ['ruby', 'emerald', 'diamond', 'pearl', 'sapphire', 'opal', 'amber', 'jade', 'topaz', 'crystal'],
  sports: ['tennis', 'soccer', 'golf', 'rugby', 'hockey', 'boxing', 'cricket', 'cycling', 'rowing', 'skiing'],
  garden: ['rose', 'tulip', 'daisy', 'lily', 'fern', 'ivy', 'hedge', 'bench', 'pond', 'seed'],
  castle: ['knight', 'tower', 'moat', 'crown', 'throne', 'dragon', 'sword', 'shield', 'banner', 'gate'],
  forest: ['oak', 'pine', 'vale', 'owl', 'fox', 'deer', 'acorn', 'trail', 'cabin', 'mushroom'],
  city: ['bridge', 'tunnel', 'subway', 'street', 'taxi', 'museum', 'statue', 'skyline', 'traffic', 'avenue'],
};
